name: see_pr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_blue_plus: ^1.32.8
  flutter_mjpeg: ^2.0.3
  camera: ^0.10.6
  url_launcher: ^6.3.0
  http: ^0.13.6
  tflite_flutter: ^0.12.1
  image_picker: ^1.1.0
  image: ^4.2.0
  flutter_tesseract_ocr: ^0.4.30
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/models/best_int8 (1).tflite
  uses-material-design: true
